spring:
  application:
    name: repository-adapter-pattern

# H2 Database Configuration

    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: password

  # JPA Configuration
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true